proxy server {
    default_fallback = no
}

home_server sgp_legacy {
    type = auth+acct
    ipaddr = 192.168.140.1
    port = 2051
    secret = sgp@radius
    response_window = 10
    zombie_period = 40
    revive_interval = 120
    status_check = none
}

home_server_pool sgp_legacy_pool {
    type = fail-over
    home_server = sgp_legacy
}

realm sgp_legacy {
    auth_pool = sgp_legacy_pool
    acct_pool = sgp_legacy_pool
    nostrip
}

realm DEFAULT {
}

realm NULL {
}
